version: '3'

services:
  db:
    image: postgres:13
    container_name: nextcloud-postgres
    volumes:
      - /mnt/backup/documents/docker/private_cloud/db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_PG_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    depends_on:
      - db
    volumes:
      - /mnt/backup/documents/docker/private_cloud/nextcloud:/var/www/html
      - /mnt/backup/documents/docker/private_cloud/app/config:/var/www/html/config
      - /mnt/backup/documents/docker/private_cloud/app/custom_apps:/var/www/html/custom_apps
      - /mnt/backup/documents/docker/private_cloud/app/data:/var/www/html/data
      - /mnt/backup/documents/docker/private_cloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime
      - /mnt/backup:/mnt/backup
      - /mnt/media:/mnt/media
    environment:
      - VIRTUAL_HOST=${EXTERNAL_URL}
      - OVERWRITECLIURL=https://nextcloud.${EXTERNAL_URL}
      - OVERWRITEPROTOCOL=https
      - LETSENCRYPT_HOST=${EXTERNAL_URL}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - NEXTCLOUD_HOSTNAME='My cloud'
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.${EXTERNAL_URL}
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    volumes:
      - /mnt/backup/documents/docker/private_cloud/config_redis:/data
    restart: unless-stopped
    networks:
      - default

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/backup/documents/docker/private_cloud/config_syncthing:/config
      - /mnt/backup:/mnt/backup
    # ports:
    #   - 8384:8384 # Web UI
    #   - 22000:22000/tcp # TCP file transfers
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - default

  elasticsearch:
    image: nextcloud/aio-fulltextsearch:latest
    container_name: nextcloud-elasticsearch
    hostname: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xms512m
      - bootstrap.memory_lock=true
      - cluster.name=nextcloud
      - discovery.type=single-node
      - logger.org.elasticsearch.discovery=WARN
      - http.port=9200
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
    volumes:
      - /mnt/backup/documents/docker/private_cloud/config_elasticsearch:/usr/share/elasticsearch/data:rw
#    ports:
#      - 9200:9200
#      - 9300:9300
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8192m
    networks:
      - default

networks:
  default:
    external: true
    name: volokzhanin
