version: '3'

services:
  db:
    image: postgres:13
    container_name: nextcloud-postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_PG_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    depends_on:
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime
      - /mnt/backup/documents/:/documents
      - /mnt/backup/backup/vvy_smartphones/record_call_vvy/:/record_call_vvy
      - /mnt/backup/backup/vvy_backup_work/:/vvy_backup_work
      - /mnt/backup/backup/vvy_smartphones/camera/:/camera_vvy
      - /mnt/backup/backup/angel_smartphones/camera_device_angel/:/camera_device_angel
      - /mnt/backup/photo/:/photo
      - /mnt/backup/video/:/my videos
      - /mnt/media/share/:/share
      - /mnt/backup/cources/:/cources
      - /mnt/backup/books:/books
      - /mnt/media/pictures/wallpapers/:/wallpapers
    environment:
      - VIRTUAL_HOST=${EXTERNAL_URL}
      - OVERWRITECLIURL=https://nextcloud.${EXTERNAL_URL}
      - OVERWRITEPROTOCOL=https
      - LETSENCRYPT_HOST=${EXTERNAL_URL}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - NEXTCLOUD_HOSTNAME='My cloud'
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.${EXTERNAL_URL}
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    volumes:
      - ./config_redis:/data
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: volokzhanin
